name: Test Inputs
description: Some description

inputs:
  set_status:
    required: false
#     default: 'false'
    description: "If set to true, set the initial 'pending' status for the run"

runs:
  using: "composite"
  steps:
    - name: Show inputs
      id: output_step
      shell: bash
#       if: inputs.set_status == 'true'
      run: |
        echo "::set-output name=count::111111"
    - name: Test Aborting
#       if: ${{ always() && true }}
      shell: bash
      run: |
        echo "Hey! The job was abort and I Can see me!!!!!!"
        echo " ${{ github.action_path }}"
        echo "${{ inputs.set_status || steps.output_step.outputs.count }}"
    
      
        
