name: Print all contexts
description: Print all contexts

runs:
  using: "composite"
  steps:
    - name: Dump GitHub context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump job context
      shell: bash
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

    - name: Dump steps context
      shell: bash
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Dump runner context
      shell: bash
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Dump strategy context
      shell: bash
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"

    - name: Dump matrix context
      shell: bash
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Dump issue context
      shell: bash
      env:
        ISSUE_CONTEXT: ${{ toJson(github.issue) }}
      run: echo "$ISSUE_CONTEXT"

    - name: Show default environment variables
      shell: bash
      run: |
        echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
        echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
        echo "The run id is: $GITHUB_RUN_ID"
        echo "The GitHub Actor's username is: $GITHUB_ACTOR"
        echo "GitHub SHA: $GITHUB_SHA"
