#!/usr/bin/env bash

set -euo pipefail
time_filter="from:%27${LOGS_STARTED_AT}%27%2Cto:%27${LOGS_FINISHED_AT}%27"
dashboard_id="42af9830-1249-11ed-9499-a73b63712242"

search="match_phrase:%28kubernetes.namespace_name:${LOGS_KUBERNETES_NAMESPACE_BASE}%29"

LOGS_LINK="https://logs-ci.toptal.net/app/dashboards#/view/${dashboard_id}?_g=%28filters:!%28%28query:%28${search}%29%29%29%2Ctime:%28${time_filter}%29%29"

echo -e "\e[34mLogs: ${LOGS_LINK}\e[0m"
echo "LOGS_LINK=$LOGS_LINK" >> $GITHUB_ENV
