name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [
        synchronize, # PR was updated
        opened, # PR was open
        reopened, # PR was closed and is now open again
        ready_for_review # PR was converted from draft to open
    ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    name: "Echo 1"
    steps:
      - name: "Echo 1"
        run: |
          echo "${{ github.sha }}"
          echo "${{ github.sha1 }}"
          echo "${{ github.event.pull_request.head.sha }}"

  feature_test_testbox_GHA:
#    needs:
#      [
#        first_job
#      ]
    name: "Run testbox features on GHA"
    if: github.ref == 'refs/heads/master'
    uses: sasha370/gha-tests/.github/workflows/features.yml@master
    with:
      platform_branch: master
      talent_portal_branch: master
