name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [
        synchronize, # PR was updated
        opened, # PR was open
        reopened, # PR was closed and is now open again
        ready_for_review # PR was converted from draft to open
    ]
    
jobs:        
  first_job:
    runs-on: ubuntu-latest
    name: "Name: first_job "
    outputs:
      need_to_push: ${{ steps.first_step.outputs.need_to_push }}
    steps:
      - name: "first_step 1"
        id: first_step
        run: |
          echo "${{ github.sha }}"
          echo "::set-output name=need_to_push::true"
          echo "NEED_TO_PUSH_ENV=false" >> $GITHUB_ENV 

  test1:
    name: 'Some tests'
    needs: first_job
    if: needs.first_job.outputs.need_to_push == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Ok, first catch is Successfully!!!!"
   
  test2:
    name: 'Some tests'
    needs: first_job
    if: ${{ env.NEED_TO_PUSH_ENV == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Ok, second catch is Successfully!!!!"
