name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [
        synchronize, # PR was updated
        opened, # PR was open
        reopened, # PR was closed and is now open again
        ready_for_review # PR was converted from draft to open
    ]

jobs:
  feature_test_testbox_GHA:
    runs-on: ubuntu-latest
    name: "Run testbox features on GHA"
    if: github.ref == 'refs/heads/master'
    steps:

      - name: "Echo var"
        run: |
          echo "TESTBOX_BRANCH_TALENT_PORTAL=${{ github.head_ref}}"

      - name: "Run testbox features on GHA"
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Features
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "talent_portal_branch": "${{ github.head_ref }}" }'
