name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [
        synchronize, # PR was updated
        opened, # PR was open
        reopened, # PR was closed and is now open again
        ready_for_review # PR was converted from draft to open
    ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    name: "Echo 1"
    steps:
      - name: "Echo 1"
        run: |
          echo "Hello"

  feature_test_testbox_GHA:
    runs-on: ubuntu-latest
    needs:
      [
        first_job
      ]
    name: "Run testbox features on GHA"
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/features.yml@master
        with:
          platform_branch: master
          talent_portal_branch: master
