name: Only for tests 
on:
#  push:
#    branches: [master]
#  pull_request:
#    types: [synchronize]
#
jobs:        
  check_image:
    runs-on: ubuntu-latest
    name: "Name: first_job "
    outputs:
      need_to_push: ${{ steps.check_image_step.outputs.need_to_push }}
    steps:
      - name: "Chech that image exists"
        id: check_image_step
        run: |
          echo "::set-output name=need_to_push::true"

  push_image:
    name: 'Push to GCS'
    needs: check_image
    if: needs.check_image.outputs.need_to_push == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "OK, I'll push it!!!"

