name: Workflow Call Debug Contexts

# https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts

on:
  workflow_call:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: ENV
        run: env
      - name: JSON env
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(env) }}
      - name: JSON vars
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(vars) }}
      - name: JSON job
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(job) }}
      # The workflow is not valid. In .github/workflows/workflow_dispatch_debug_contexts.yml (Line: 16, Col: 11):
      # Error from called workflow kml/github-actions-playground/.github/workflows/workflow_call_debug_contexts.yml@main (Line: 31, Col: 20):
      # Unrecognized named-value: 'jobs'. Located at position 8 within expression: toJSON(jobs)
      # - name: JSON jobs
      #   run: |
      #     echo $context | jq --color-output .
      #   env:
      #     context: ${{ toJSON(jobs) }}
      - name: JSON steps
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(steps) }}
      - name: JSON runner
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(runner) }}
      - name: JSON secrets
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(secrets) }}
      # - name: JSON strategy
      #   run: |
      #     echo $context | jq --color-output .
      #   env:
      #     context: ${{ toJSON(strategy) }}
      # - name: JSON matrix
      #   run: |
      #     echo $context | jq --color-output .
      #   env:
      #     context: ${{ toJSON(matrix) }}
      - name: JSON needs
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(needs) }}
      - name: JSON inputs
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(inputs) }}
