name: Group A

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Group test
        # Comment used at run to hide 
        # Run echo "::group::Group A"
        run: |
          # Run specs
          RSPEC_STATUS=0
 
          echo "::group::Group A"             
          (
            ls -la
          )
          (( RSPEC_STATUS=RSPEC_STATUS || $? ))

          echo "::endgroup::"

          echo "::group::Group B"

          (
            cat 404
          )
          exit_code=$?
          (( RSPEC_STATUS=RSPEC_STATUS || $? ))
          echo "::endgroup::"

          echo "::group::Group C"
          (
            echo "Hello"
          )
          (( RSPEC_STATUS=RSPEC_STATUS || $? ))        
          echo "::endgroup::"
          echo "status: $status"
          
          if [ $RSPEC_STATUS -eq 0 ]; then
            exit 0
          else
            exit 1
          fi  
