name: Fail fast

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  job1:
    uses: ./.github/workflows/wf_called_pause.yml
    with:
      pause: 5
      release_candidate: false
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: |
          sleep 10
          exit 1
          
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.3
  
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: |
          sleep 60
          exit 0
          
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.3
  
  
  get_results: 
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    if: ${{ !cancelled() }}
    steps:          
      - name: Prepare result status
        shell: bash
        id: prepare_status
        env:
          context: ${{ toJSON(needs) }}
        run: |
          echo $context | jq --color-output .

          rc_failed=${{ contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')}}
          echo "RC failed?: $rc_failed"

          if [ $rc_failed == 'true' ]; then
            echo "emoji=:redex:" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "emoji=:green_heart:" >> $GITHUB_OUTPUT
          fi
