name: Fail fast

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Job 1
        run: |
          sleep 5
          exit 0
  
  job2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Job 2
        run: |
          sleep 10
          exit 1
  
  job3:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Job 3
        run: |
          sleep 15
          exit 0
  
  
  check_results:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    if: always()
    steps:
      - name: Check Job Results
        run: |
          echo needs.job1.outputs.result
          echo needs.job2.outputs.result
          echo needs.job3.outputs.result
          if [[ needs.job1.outputs.result != '0' || needs.job2.outputs.result != '0' || needs.job3.outputs.result != '0' ]]; then
            echo "One or more jobs failed. Failing the build."
            exit 1
          else
            echo "All jobs passed."
          fi
