name: Fail fast

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Job 1
        uses: ./.github/workflows/wf_called_pause.yml.yml
        with:
          pause: 5
          
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.3
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        uses: ./.github/workflows/wf_called_pause.yml.yml
        with:
          pause: 10
          
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.3
  
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        uses: ./.github/workflows/wf_called_pause.yml.yml
        with:
          pause: 60
          
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.3
  
  
  check_results:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    if: always()
    steps:
      - name: Sent Slack message
        run: |
          echo "I'm a Slack message"
          
      - name: Check Job Results
        run: |
          if [[ needs.job1.outputs.result != '0' || needs.job2.outputs.result != '0' || needs.job3.outputs.result != '0' ]]; then
            echo "One or more jobs failed. Failing the build."
            exit 1
          else
            echo "All jobs passed."
          fi

