name: Fail fast

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  job1:
    uses: ./.github/workflows/wf_called_pause.yml
    with:
      pause: 5
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: |
          sleep 10
          exit 0
          
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.3
  
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: |
          sleep 60
          exit 0
          
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.3
  
  
  check_results:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    if: always()
    steps:
      - name: Sent Slack message
        run: |
          echo "I'm a Slack message"
          
      - name: Check Job Results
        run: |
          if [[ needs.job1.outputs.result != '0' || needs.job2.outputs.result != '0' || needs.job3.outputs.result != '0' ]]; then
            echo "One or more jobs failed. Failing the build."
            exit 1
          else
            echo "All jobs passed."
          fi

