name: Features

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:
    inputs:
      platform_branch:
        description: 'Input Platform branch (default master)'
        required: false
        default: 'master_WD'
      talent_portal_branch:
        description: 'Input Talent Portal branch (default master)'
        required: false
        default: 'master_WD'

  workflow_call:
    inputs:
      platform_branch:
        type: string
        description: 'Input Platform branch (default master)'
        required: false
        default: 'master_WC'
      talent_portal_branch:
        type: string
        description: 'Input Talent Portal branch (default master)'
        required: false
        default: 'master_WC'

jobs:
  features:
    name: Run features
    runs-on: ubuntu-latest
    steps:

      - name: Set PR's author github teams
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          echo "Author:  ${{ env.PR_AUTHOR }}."
          echo "Author by GH:  ${{ github.actor }}."
          
      - uses: octokit/graphql-action@v2.x
        id: get_author_teams
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query organization(login: "toptal") {
              teams(first: 100, userLogins: [${{ github.actor }}]) {
                totalCount
                edges {
                  node {
                  name
                  description
                  }
                }
              }
            }

      - run: "echo 'Teams: ${{ steps.get_author_teams.outputs.data }}'"



      - name: Set Branches
        run: |
          echo "TESTBOX_BRANCH_PLATFORM=${{ inputs.platform_branch || github.event.inputs.platform_branch }}" >> $GITHUB_ENV
          echo "TESTBOX_BRANCH_TALENT_PORTAL=${{ inputs.talent_portal_branch|| github.event.inputs.talent_portal_branch }}" >> $GITHUB_ENV
      - name: Show Branch
        run: |
          echo ${{ env.TESTBOX_BRANCH_PLATFORM }}
          echo ${{ env.TESTBOX_BRANCH_TALENT_PORTAL }}

