name: Features

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:
    inputs:
      platform_branch:
        description: 'Input Platform branch (default master)'
        required: true
        default: 'master_WD'
      talent_portal_branch:
        description: 'Input Talent Portal branch (default master)'
        required: true
        default: 'master_WD'

  workflow_call:
    inputs:
      platform_branch:
        type: string
        description: 'Input Platform branch (default master)'
        required: true
        default: 'master_WC'
      talent_portal_branch:
        type: string
        description: 'Input Talent Portal branch (default master)'
        required: true
        default: 'master_WC'
      ANVIL_PARENT_BUILD_ID:
        type: string
        description: 'Parent Build ID from Anvil'
        required: false
        default: ''

jobs:
  features:
    name: Run features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Trigger the action
        uses: ./.github/actions/test

      - name: Set PR's author github teams
        run: |
          echo "ANVIL_PARENT_BUILD_ID:  ${{ inputs.ANVIL_PARENT_BUILD_ID }}"
          sleep 20

      - name: Set Branches
        run: |
          echo "TESTBOX_BRANCH_PLATFORM=${{ inputs.platform_branch || github.event.inputs.platform_branch }}" >> $GITHUB_ENV
          echo "TESTBOX_BRANCH_TALENT_PORTAL=${{ inputs.talent_portal_branch|| github.event.inputs.talent_portal_branch }}" >> $GITHUB_ENV
      - name: Show Branch
        run: |
          echo ${{ env.TESTBOX_BRANCH_PLATFORM }}
          echo ${{ env.TESTBOX_BRANCH_TALENT_PORTAL }}
      - name: Run always
        run: |
          echo "++++++++++++++++ This Always from current workflow"
        if: ${{ always() }}

