name: Features

on:
#  push:
#    branches:
#      - 'master'
#  pull_request:
#    types: [opened, synchronize]

  workflow_dispatch:
    inputs:
      platform_branch:
        description: 'Input Platform branch (default master)'
        required: true
        default: 'master_WD'
      talent_portal_branch:
        description: 'Input Talent Portal branch (default master)'
        required: true
        default: 'master_WD'

  workflow_call:
    inputs:
      platform_branch:
        type: string
        description: 'Input Platform branch (default master)'
        required: true
        default: 'master_WC'
      talent_portal_branch:
        type: string
        description: 'Input Talent Portal branch (default master)'
        required: true
        default: 'master_WC'
      ANVIL_PARENT_BUILD_ID:
        type: string
        description: 'Parent Build ID from Anvil'
        required: false
        default: ''

jobs:
  check-workflow-call:
    name: Check if it's a workflow_call
    if: github.event_name != 'workflow_call'
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo HERE ARE WE GO!!!!
  
  
  features:
    name: Run features
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Show context
        uses: ./.github/actions/print_context/

      - name: Trigger the action
        uses: ./.github/actions/test
        id: action

      - name: Set PR's author github teams
        run: |
          echo ${{ steps.action.outputs.BASE_NAME_OUT }}
          echo "ANVIL_PARENT_BUILD_ID:  ${{ inputs.ANVIL_PARENT_BUILD_ID }}"
          sleep 20

      - name: Set Branches
        run: |
          echo "TESTBOX_BRANCH_PLATFORM=${{ inputs.platform_branch || github.event.inputs.platform_branch }}" >> $GITHUB_ENV
          echo "TESTBOX_BRANCH_TALENT_PORTAL=${{ inputs.talent_portal_branch|| github.event.inputs.talent_portal_branch }}" >> $GITHUB_ENV
      - name: Show Branch
        run: |
          echo ${{ env.TESTBOX_BRANCH_PLATFORM }}
          echo ${{ env.TESTBOX_BRANCH_TALENT_PORTAL }}
      - name: Run always
        run: |
          echo "++++++++++++++++ This Always from current workflow"
          echo ${{ github.repository }} | awk -F '/' '{ print $2 }'
        if: ${{ always() }}
      - name: Set cluster
        id: set_cluster
        shell: bash
        run: |
          repo_name=$(echo ${{ github.repository }} | awk -F '/' '{ print $2 }')
          cluster_name=$([ $repo_name = 'gha-tests1' ] && echo 'testbox' || echo 'testbox-1')
          echo "::set-output name=cluster_name::${cluster_name}"
          
      - uses: ruby/setup-ruby@v1
        with:
           cluster_name: ${{ steps.set_cluster.outputs.cluster_name }}
           bundler-cache: true
           working-directory: ./platform
