name: Features

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize]


  workflow_dispatch:
    inputs:
      platform_branch:
        description: 'Input Platform branch (default master)'
        required: true
        default: 'master_WD'
      talent_portal_branch:
        description: 'Input Talent Portal branch (default master)'
        required: true
        default: 'master_WD'

  workflow_call:
    inputs:
      platform_branch:
        type: string
        description: 'Input Platform branch (default master)'
        required: true
        default: 'master_WC'
      talent_portal_branch:
        type: string
        description: 'Input Talent Portal branch (default master)'
        required: true
        default: 'master_WC'

jobs:
  features:
    name: Run features
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_pr_author_teams
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TEST_REPO }}
          INPUT_AUTHOR: ${{ github.event.pull_request.user.login }}
        with:
          query: |
            query team($author:String!) {
              organization(login: "toptal") {
                teams(first: 100, userLogins: [$author]) {
                  edges {
                    node {
                      slug
                    }
                  }
                }
              }
            }

      - name: Set PR_AUTHOR_TEAMS env
        id: set_teams
        shell: bash
        env:
          teams_dump: ${{  }}
        run: |
          raw_teams="${{ join(fromJSON(steps.get_pr_author_teams.outputs.data).organization.teams.edges.*.node.slug, ' ') }}"
          teams="$(echo "$raw_teams" | sed '/^$/!s/[^ ]* */@toptal\/&/g')"
          echo "::set-output name=PR_AUTHOR_TEAMS::${teams}"
      - run: |
          echo "PR_AUTHOR_TEAMS=${{ steps.set_teams.outputs.pr_author_teams }}" >> $GITHUB_ENV
      - run: |       
          echo ${{env.PR_AUTHOR_TEAMS}}
#      - name:  Set PR's author github teams VER 2
#        uses: actions/github-script@v3
#        with:
#          github-token: ${{secrets.GHA_TEST_REPO}}
#          script: |
#            const query = `query team($author:String!) {
#                organization(login: "toptal") {
#                  teams(first: 100, userLogins: [$author]) {
#                    edges {
#                      node {
#                        slug
#                      }
#                    }
#                  }
#                }
#            }`;
#            const variables = {
#              author: '${{ github.actor }}',
#            }
#            const result = await github.graphql(query, variables)
#            console.log(result)
#
#            const data = result | jq '.data.organization.teams.edges | .[].node.slug'
#            console.log(data)



      - name: Set Branches
        run: |
          echo "TESTBOX_BRANCH_PLATFORM=${{ inputs.platform_branch || github.event.inputs.platform_branch }}" >> $GITHUB_ENV
          echo "TESTBOX_BRANCH_TALENT_PORTAL=${{ inputs.talent_portal_branch|| github.event.inputs.talent_portal_branch }}" >> $GITHUB_ENV
          echo ${{github.started_at}}
      - name: Show Branch
        run: |
          echo ${{ env.TESTBOX_BRANCH_PLATFORM }}
          echo ${{ env.TESTBOX_BRANCH_TALENT_PORTAL }}
