name: Features

on:
  push:
    branches:
      - '*features*'
  workflow_dispatch:
    inputs:
      platform_branch:
        description: 'Input Platform branch (default master)'
        required: true
        default: master
      talent_portal_branch:
        description: 'Input Talent Portal branch (default master)'
        required: true
        default: master

  workflow_call:
    inputs:
      platform_branch:
        type: string
        description: 'Input Platform branch (default master)'
        required: true
        default: master
      talent_portal_branch:
        type: string
        description: 'Input Talent Portal branch (default master)'
        required: true
        default: master

jobs:
  features:
    name: Run features
    runs-on: ubuntu-latest
    steps:
      - name: Set Branches
        run: |
          echo "TESTBOX_BRANCH_PLATFORM=${{ github.event_name == 'workflow_call' && inputs.platform_branch || github.event.inputs.platform_branch}}" >> $GITHUB_ENV
          echo "TESTBOX_BRANCH_TALENT_PORTAL=${{ github.event_name == 'workflow_call' && inputs.talent_portal_branch|| github.event.inputs.talent_portal_branch }}" >> $GITHUB_ENV
      - name: Show Branch
        run: |
          echo ${{ env.TESTBOX_BRANCH_PLATFORM }}
          echo ${{ env.TESTBOX_BRANCH_TALENT_PORTAL }}
