name: Features

on:
  push:
    branches:
      - '*features*'
  workflow_dispatch:
    inputs:
      platform_branch:
        description: 'Input Platform branch (default master)'
        required: false
      talent_portal_branch:
        description: 'Input Talent Portal branch (default master)'
        required: false

  workflow_call:
    inputs:
      platform_branch:
        type: string
        description: 'Input Platform branch (default master)'
        required: false
      talent_portal_branch:
        type: string
        description: 'Input Talent Portal branch (default master)'
        required: false

jobs:
  features:
    name: Run features
    runs-on: ubuntu-latest
    steps:
      - name: Set Branches
        run: |
          echo ${{ inputs.platform_branch }}
          echo ${{ inputs.talent_portal_branch }}
          echo ${{ github.event.inputs.platform_branch }} 
          echo ${{ github.event.inputs.talent_portal_branch }}
          
          echo "TESTBOX_BRANCH_PLATFORM=${{ inputs.platform_branch || github.event.inputs.platform_branch || 'master' }}" >> $GITHUB_ENV
          echo "TESTBOX_BRANCH_TALENT_PORTAL=${{ inputs.talent_portal_branch|| github.event.inputs.talent_portal_branch || 'master' }}" >> $GITHUB_ENV
      - name: Show Branch
        run: |
          echo ${{ env.TESTBOX_BRANCH_PLATFORM }}
          echo ${{ env.TESTBOX_BRANCH_TALENT_PORTAL }}
