name: Features

on:
  push:
    branches:
      - '*-features*'
  workflow_dispatch:
    inputs:
      platform_branch:
        description: 'Input Platform branch (default master)'
        required: false
      talent_portal_branch:
        description: 'Input Talent Portal branch (default master)'
        required: false


jobs:
  features:
    name: Run features
    runs-on: ubuntu-latest
    steps:
      - name: Set Branches
        run: |
          echo "TESTBOX_BRANCH_PLATFORM=${{ github.event.inputs.platform_branch || 'master' }}" >> $GITHUB_ENV
          echo "TESTBOX_BRANCH_TALENT_PORTAL=${{ github.event.inputs.talent_portal_branch || 'master' }}" >> $GITHUB_ENV
 
 
 
 
 
