name: Flows

on:
  workflow_dispatch:
    inputs:
      sha:
        description: Git reference commit
        type: string
        required: true

  issue_comment:
    types: [ created ]

concurrency:
  group: >-
    flows
    ${{ github.repository }}
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{ github.event.issue.number || github.ref }}
    ${{ github.triggering_actor }}
  cancel-in-progress: true

jobs:
  check_necessity:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_dispatch') ||
      (inputs.is_workflow_call == 'true') ||
      (
        github.event.issue.pull_request &&
        (
          contains(github.event.comment.body, '@toptal-bot run ') &&
          (
            contains(github.event.comment.body, 'flows tests') ||
            contains(github.event.comment.body, 'backend pact') ||
            contains(github.event.comment.body, 'default') ||
            contains(github.event.comment.body, 'mergecheck')
          )
        )
      )
    outputs:
      continue: ${{ steps.check.outputs.continue }}
    steps:
      - name: Checkout platform
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha || github.sha }}
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_ignore: |
            - **/yarn.lock
            - **/package.json
            - docs/**
            - **.md
            - **.js
            - **.ejs
            - **.jsx

      - name: Check if any files have changed
        env:
          any_changed: ${{ steps.changed-files.outputs.any_changed }}
        run: |
          if [ $any_changed == 'true' ] ; then
            echo "Backend files have changed."
            echo "List all the files that have changed: ${{ steps.changed-files.outputs.all_changed_files }}"
          else
            echo "No backend files have changed. Skip flows tests."
            exit 0
          fi

  flows:
    name: ${{ matrix.mode }}
    needs: check_necessity
    if: ${{ !cancelled() && needs.check_necessity.outputs.continue == 'true'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [ explore, test ]

    steps:
      - name: Checkout platform
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Run flows ${{ matrix.mode }}
        run: |
          echo "Done"
