name: Flows

on:
  workflow_dispatch:
    inputs:
      sha:
        description: Git reference commit
        type: string
        required: true
      force_build:
        description: 'Force build execution?'
        type: string
        required: false
        default: 'false'

  workflow_call:
    inputs:
      sha:
        description: Git reference commit
        type: string
        required: true
      is_workflow_call:
        description: 'Is workflow call?'
        type: string
        required: false
        default: 'true'

jobs:
  register_build:
    name: Register build in Anvil
    runs-on: ubuntu-latest
    if: inputs.is_workflow_call != 'true'
    timeout-minutes: 3
    continue-on-error: true
    outputs:
      skip_build: ${{ steps.skip-build.outputs.skip_build }}
    steps:
      - name: Register build in Anvil
        id: skip-build
        shell: bash
        run: |
          echo "Register build in Anvil"
          echo "skip_build=true" >> $GITHUB_OUTPUT

      - name: Set check status if build skipped
        if: ${{ inputs.force_build != 'true' && steps.skip-build.outputs.skip_build == 'true' }}
        uses: actions/github-script@v6
        env:
          STATUS_STATE: 'success'
          STATUS_CHECK_NAMES: '["Flows test / explore", "Flows test / test"]'
          BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
        with:
          script: |
            const { owner, repo } = context.issue;
            const checkNames = JSON.parse(process.env.STATUS_CHECK_NAMES);

            for (const checkName of checkNames) {
              await github.rest.repos.createCommitStatus({
                owner,
                repo,
                sha: context.sha,
                context: checkName,
                state: process.env.STATUS_STATE,
                target_url: process.env.BUILD_URL
              });
            }

  flows:
    name: ${{ matrix.mode }}
    needs: register_build
    if: ${{ !cancelled() && inputs.force_build != 'true' && needs.register_build.outputs.skip_build != 'true'}}
    runs-on: ubuntu-latest
    env:
      STATUS_CHECK_NAME: Flows test / ${{ matrix.mode }}
      BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
      SKIP_BUILD: ${{ needs.register_build.outputs.skip_build }}
    strategy:
      matrix:
        mode: [ explore, test ]
    steps:
      - name: JSON event
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(github.event) }}
      - name: JSON job
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(job) }}
      - name: JSON inputs
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(inputs) }}
      - name: JSON github
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(github) }}

      - name: Set status check - pending
        uses: actions/github-script@v6
        if: ${{ inputs.is_workflow_call != 'true' }}
        env:
          STATUS_STATE: pending
        with:
          script: |
            const { owner, repo } = context.issue;
            console.log(context);
            console.log(context.sha);
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              context: process.env.STATUS_CHECK_NAME,
              state: process.env.STATUS_STATE,
              target_url: process.env.BUILD_URL
            })

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so lerna command --since origin/master can work properly
          fetch-depth: 0
          ref: ${{ inputs.sha || github.ref }}

      - name: Run flows ${{ matrix.mode }}
        run: |
          echo "Done"

      - name: Set status check - success / failure / error
        uses: actions/github-script@v6
        if: ${{ always() && inputs.is_workflow_call != 'true' }}
        env:
          STATUS_STATE: ${{ job.status != 'cancelled' && job.status || 'error' }}
        with:
          script: |
            const { owner, repo } = context.issue;
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              context: process.env.STATUS_CHECK_NAME,
              state: process.env.STATUS_STATE,
              target_url: process.env.BUILD_URL
            })
