name: Flows

on:
  workflow_dispatch:
    inputs:
      sha:
        description: Git reference commit
        type: string
        required: true

  workflow_call:
    inputs:
      sha:
        description: Git reference commit
        type: string
        required: true
      is_workflow_call:
        description: 'Is workflow call?'
        type: string
        required: false
        default: 'true'

  issue_comment:
    types: [ created ]

jobs:
  check_necessity:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_dispatch') ||
      (inputs.is_workflow_call == 'true') ||
      (
        github.event.issue.pull_request &&
        (
          contains(github.event.comment.body, '@toptal-bot run ') &&
          (
            contains(github.event.comment.body, 'flows tests') ||
            contains(github.event.comment.body, 'backend pact') ||
            contains(github.event.comment.body, 'default') ||
            contains(github.event.comment.body, 'mergecheck')
          )
        )
      )
    steps:
      - name: JSON github
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(github) }}
      - name: JSON event
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(github.event) }}

      - name: Checkout platform
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha || 'test-skip-3' || github.sha }}

#      - name: show info
#        run: |
#          `git diff --name-only --diff-filter=ACMR #{target_branch}`.split("\n")

#IF it is a issue_comment then Actions tries to get diff for Master branch even if I check out a different branch.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_ignore: |
             **/yarn.lock
             **/package.json
             docs/**
             **.md
             **.js
             **.ejs
             **.jsx

      - name: Check if any files have changed
        env:
          any_changed: ${{ steps.changed-files.outputs.any_changed }}
        run: |
          if [ $any_changed == 'true' ] ; then
            echo "Backend files have changed."
            echo "List all the files that have changed: ${{ steps.changed-files.outputs.all_changed_files }}"
          else
            echo "No backend files have changed. Skip flows tests."
            exit 0
          fi

  flows:
    name: ${{ matrix.mode }}
    needs: check_necessity
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [ explore, test ]
    steps:
      - name: Checkout platform
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha || 'flow-test-1' || github.sha }}

      - name: Run flows ${{ matrix.mode }}
        run: |
          echo "Done"
