name: Gems specs

on:
  workflow_dispatch:
    inputs:
      sha:
        description: Git reference commit.
        type: string
        required: true

  pull_request:
    # Keep paths in sync with .github/workflows/skip_gems_specs.yml
    paths:
      - 'gems/**'

concurrency:
  group: >-
    gems-specs
    ${{ github.repository }}
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{ github.event.issue.number || github.ref }}
    ${{ github.triggering_actor }}
  cancel-in-progress: true

jobs:
  gems-specs:
    name: Gems specs
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Run specs
        shell: bash
        run: |
          echo "Done"
