name: Inputs test

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:
    inputs:
      logs_started_at:
        description: 'Logs Started At'
        required: false

      logs_finished_at:
        description: 'Logs Finished At'
        required: false
     
      anvil_parent_build_id:
        description: Parent CiBuild ID
        type: number
        required: false
        
  workflow_call:


jobs:
  logs_link:
    name: Run Logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: JSON inputs
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(inputs) }}
          
      - id: generate_kibana_logs_link
        uses: ./.github/actions/generate-kibana-logs-link/
        with:
          logs_started_at: ${{ inputs.logs_started_at }}
          logs_finished_at: ${{ inputs.logs_finished_at }}

      - shell: bash
        run: |
          ${PWD}/.github/workflows/generate_summary
          echo ${{github.workflow}}
        env:
          KIBANA_LOGS_LINK: ${{ steps.generate_kibana_logs_link.outputs.logs_link }}


