name: Verify contracts for "Platform (async)" provider

permissions:
  contents: read
  id-token: write
  actions: write
  statuses: write

on:
  workflow_call:
    inputs:
      sha:
        description: Git reference commit.
        type: string
        required: true
      ref_name:
        description: Branch name.
        type: string
        required: true
      run_with_wip:
        description: Run with WIP contracts.
        type: boolean
        required: true
      set_status:
        description: 'Set check status?'
        type: string
        required: false
        default: 'false'

jobs:
  verify:
    name: Platform (async)
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      STATUS_CHECK_NAME: Provider / Platform (async)
      BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}

    steps:
      - name: Set status check - pending
        uses: actions/github-script@v6
        env:
          STATUS_STATE: pending
        with:
          script: |
            const { owner, repo } = context.issue;
            console.log(context);
            console.log(context.sha);
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              context: process.env.STATUS_CHECK_NAME,
              state: process.env.STATUS_STATE,
              target_url: process.env.BUILD_URL
            })

      - name: JSON job
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(job) }}

      - name: Do something
        shell: bash
        run: |
          exit 1
          echo "Provider Platform async contracts verification"

      - name: Set status check - success / failure / error
        uses: actions/github-script@v6
        if: always()
        env:
          STATUS_STATE: ${{ job.status != 'cancelled' && job.status || 'error' }}
        with:
          script: |
            const { owner, repo } = context.issue;
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              context: process.env.STATUS_CHECK_NAME,
              state: process.env.STATUS_STATE,
              target_url: process.env.BUILD_URL
            })

