name: Release candidate

on:
 push:
   branches: [ master ]

jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Success job
        shell: bash
        run: |
          echo 'Green'

  second_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Failed job
        shell: bash
        run: |
          exit 1
  context:
    runs-on: ubuntu-latest
    steps:
      - name: ENV
        run: env
      - name: JSON env
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(env) }}
      - name: JSON vars
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(vars) }}
      - name: JSON job
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(job) }}
      - name: JSON steps
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(steps) }}
      - name: JSON runner
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(runner) }}
      - name: JSON secrets
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(secrets) }}
      - name: JSON needs
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(needs) }}
      - name: JSON inputs
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(inputs) }}

  get_results: 
    runs-on: ubuntu-latest
    steps:          
      - name: Report failure to Slack
        if: ${{ failure() }}
        shell: bash 
        run: |
          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with ${GITHUB_SHA::7} is :redex:."

      - name: Report success to Slack
        if: ${{ success() }}
        shell: bash 
        run: |
          echo "RC <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_id}}> with ${GITHUB_SHA::7} is :green_heart:."
