name: Skip


on:
  push:
    branches: [ 'devx-2297-gems-specs' ]

  workflow_dispatch:
    inputs:
      sha:
        description: Git reference commit.
        type: boolean
        required: false

jobs:
  step1:
    if: ${{ inputs.sha }}
    runs-on: ubuntu-latest

    steps:
      - name: First
        run: |
          echo 1

  check:
    
    needs: [step1]
    runs-on: ubuntu-latest

    steps:
      - name: Second
        run: |
          echo 2
