name: Gems specs

on:
  pull_request:
    # Keep paths in sync with .github/workflows/gems_specs.yml
    paths-ignore:
      - 'gems/**'

concurrency:
  group: >-
    skip-gems-specs
    ${{ github.repository }}
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{ github.event.issue.number || github.ref }}
    ${{ github.triggering_actor }}
  cancel-in-progress: true

jobs:
  gems-specs:
    name: Gems specs
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check required"'
