name: Test the event when rerun is triggered

on:
  workflow_dispatch:
    inputs:
      are_you_sure:
        description: 'Are you sure?'
        required: false
        default: false

jobs:
  test:
    if: >
      !( github.event_name == 'workflow_dispatch' && github.event.inputs.are_you_sure == 'true' && github.run_number > 1 )  ||
      ( github.event_name == 'workflow_dispatch' )

    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: SMT
        run: echo "SMT"

  context:
    name: Show context
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Show context
        uses: ./.github/actions/print_context/
