name: Test Inputs

on:
#  push:
#    branches:
#      - 'test_inputs'

  workflow_call:
    inputs:
      set_status:
        default: false
        type: boolean
        description: "If set to true, set the initial 'pending' status for the run"

jobs:
  features:
    name: Run inputs
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        if: inputs.set_status
        run: |
          echo "Дефолтный инпут был False, этой строчки не должно быть"
      
      
        
