name: CI rewrite

on:
  push:
    branches:
      - test_rewrite_actions

jobs:
  rewrite:
    name: rewrite
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          ecssho "Say Hello"


