name: Test the event when rerun is triggered

on:
  workflow_dispatch:
    inputs:
      are_you_sure:
        description: 'Are you sure?'
        required: false
        default: false

jobs:
  test:

    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: SMT
        if: github.event.inputs.are_you_sure == 'true'
        run: echo "SMT"
        
      - name: Cancel if RC re-run manually
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.are_you_sure == 'true' && github.run_attempt > 1
        shell: bash 
        run: |
          echo "It is forbidden to restart specs for RC."
          echo "Please use 'workflow_dispatch' with 'Platform branch: ${{ github.sha }}' and 'release_candidate: false' instead."
          exit 1    

  context:
    name: Show context
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Show context
        uses: ./.github/actions/print_context/
