name: Trigger CD

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fail 1
        id: fail1
        run: |
          false

  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Fail 1
        id: fail1
        run: |
          false
   
  test2: 
    runs-on: ubuntu-latest
    steps:
      - name: Fail 3
        id: fail3
        run: |
          # let processes to fail
          set +e
          cat 505
          echo "exit_status=$?" >> $GITHUB_OUTPUT
          echo "XYZ"
  test3:
    runs-on: ubuntu-latest
    steps:
      - name: Success 1
        id: success1
        run: |
          true
  
  final:
    runs-on: ubuntu-latest
    needs: [test, test1, test2, test3]
    steps:
      - name: Calculate conclusion
        run: |
          echo "Here we go"

