name: Trigger CD

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fail 1
        id: fail1
        run: |
          sleep 5
          true

  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Fail 1
        id: fail1
        run: |
          sleep 5
          true
   
  test2: 
    runs-on: ubuntu-latest
    steps:
      - name: Fail 3
        id: fail3
        run: |
          false
  test3:
    runs-on: ubuntu-latest
    steps:
      - name: Success 1
        id: success1
        run: |
          sleep 5
          true
  
  final:
    runs-on: ubuntu-latest
    needs: [test, test1,  test3]
    steps:
      - name: Calculate conclusion
        run: |
          echo "Here we go"

