name: Set pause
on: 
  workflow_call:
    inputs:
      pause: 
        required: true
        type: string
  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        id: pause
        run: |
          sleep ${{ inputs.pause }}
      
      - name: Context
        run: | 
          echo ${{github.event_name}}
          
      - name: Fail fast
        if: steps.pause.outcome == 'failure' && github.event_name == 'workflow_call'
        uses: andymckay/cancel-action@0.3
