name: Set pause
on: 
  workflow_call:
    inputs:
      pause: 
        required: true
        type: string
      release_candidate: 
        required: false
        type: boolean
  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
                
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Sleep
        id: pause
        run: |
          sleep ${{ inputs.pause }}
          echo ${{github.inputs}}
          exit 1


      - name: Fail fast
        if: (failure() && github.inputs.release_candidate == 'false')
        uses: andymckay/cancel-action@0.3
