name: Set pause
on: 
  workflow_call:
    inputs:
      pause: 
        required: true
        type: string
      release_candidate: 
        required: false
        type: boolean
  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
name: Workflow Call Debug Contexts

# https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts

on:
  workflow_call:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: ENV
        run: env
      - name: JSON env
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(env) }}
      - name: JSON vars
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(vars) }}
      - name: JSON job
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(job) }}

      - name: JSON steps
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(steps) }}
      - name: JSON runner
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(runner) }}
      - name: JSON secrets
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(secrets) }}

      - name: JSON needs
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(needs) }}
      - name: JSON inputs
        run: |
          echo $context | jq --color-output .
        env:
          context: ${{ toJSON(inputs) }}
        
      - name: Sleep
        id: pause
        run: |
          sleep ${{ inputs.pause }}
          echo ${{github.workflow_run.inputs}}
          echo ${{github.workflow_run.inputs.pause}}
          echo ${{github.workflow_run.inputs.release_candidate}}
          exit 1


      - name: Fail fast
        if: (failure() && github.inputs.release_candidate == 'false')
        uses: andymckay/cancel-action@0.3
