name: WF initialiser

on:
  push:
    branches:
      - 'test_inputs'

jobs:
  features:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
  inputs_test:
    uses: ./.github/workflows/test_inputs.yml
#    with:
#      set_status: true
