name: WF initializer

on:
  push:
    branches:
      - 'master'

jobs:
  features:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - name: Features
        uses: ./.github/workflows/features.yml
        with: 
          platform_branch: 'master'
          talent_portal_branch: 'master'
  inputs_test:
    uses: ./.github/workflows/features.yml
    with: 
      platform_branch: 'master'
      talent_portal_branch: 'master'
