name: Set pause
on: 
  workflow_call:
    inputs:
      pause: 
        required: true
        type: string
  

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        id: pause
        run: |
          sleep ${{ inputs.pause }}
          exit 1
          
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Fail fast
        if: steps.pause.outcome == 'failure'
        uses: andymckay/cancel-action@0.3
